services:
  escola-db:
    image: postgres:15-alpine
    container_name: escola-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - escola-network

  escola-backend:
    build: 
      context: ./escola-backend
      dockerfile: Dockerfile
    container_name: escola-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@escola-db:5432/escola
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CHROMIUM_PATH=/usr/bin/chromium-browser
    ports:
      - "3000:3000"
    depends_on:
      - escola-db
    volumes:
      - ./escola-backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - escola-network
    command: npm run start:dev
    restart: unless-stopped

  escola-frontend:
    container_name: escola-frontend
    build:
      context: ./escola-frontend
    expose:
      - '3001'
    environment:
      - VITE_API_BASE_URL=${API_URL:-http://escola-backend:3000}
    networks:
      - escola-network
    depends_on:
      - escola-backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  escola-network:
    driver: bridge